### ISSUE TITLE
Transfer ownership of mangadex-api?

### ISSUE THREAD

**Issue by gondolyr** [tonymushah/mangadex-api#1]
Hi, I'm the former maintainer of the [mangadex-api](https://crates.io/crates/mangadex-api) crate. Would you like to take ownership of it? Having multiple crates with similar names will only cause confusion imo.

**Comment by gondolyr** [comment]
Seems like the MangaDex team made their [API docs repo](https://gitlab.com/mangadex-pub/mangadex-api-docs) public since I last worked on this so you could check the Atom feed of the [`api.yaml`](https://gitlab.com/mangadex-pub/mangadex-api-docs/-/commits/main/static/api.yaml) file, which would convenient to scan for any changes to their API.

Feed URL: https://gitlab.com/mangadex-pub/mangadex-api-docs/-/commits/main/static/api.yaml?format=atom

**Comment by tonymushah** [comment]
Sounds goods, i need to maintain these crates because i need them for my mangareader app. 
But, i need to know what feature you wanted to add in the crate.

**Comment by gondolyr** [comment]
> i need to maintain these crates because i need them for my mangareader app.

My intention is not to force the burden of maintaining the original crate if you don't want to. If you would prefer to maintain a fork solely for your reader app, that could be a better path.

> i need to know what feature you wanted to add in the crate.

I have a bunch of stuff :sweat_smile: ...
There are probably more I can list but this is already a lot.

* I'm not sure that breaking up the project into workspaces (`mangadex-api-types`, `mangadex-api-schema`) was worth the trouble. It might be good to put them back into a single workspace but I can't say which is better honestly.
* The API could be made more ergonomic. The builder pattern felt clunky whenever I tried to use my own library.
    ```rs
    let manga = client
        .manga()
        .aggregate()
        .manga_id(&manga_id)
        .translated_language(languages)
        .build()
        .unwrap()
        .send()
        .await;
    ```
* More structs and modules should be made public. This is currently making it impossible for some to compile their programs simply because they can't define the type in their functions.
    ```
    error[E0603]: module `manga_aggregate` is private
      --> src/events/components/manga_reader.rs:48:132
       |
    48 | ...ponentInteraction, manga: mangadex_api::v5::schema::manga_aggregate::MangaAggregate) {
       |                                                        ^^^^^^^^^^^^^^^ private module
       |
    note: the module `manga_aggregate` is defined here
      --> /home/jp/.cargo/registry/src/github.com-1ecc6299db9ec823/mangadex-api-1.3.0/src/v5/schema.rs:14:1
       |
    14 | mod manga_aggregate;
       | ^^^^^^^^^^^^^^^^^^^^
    ```
* The `v5` module is probably unnecessary. I made it because of the potential of future major API versions since at the time I made it, there was a `v2` and `v5` of the MangaDex API.
* I'd like to have the `thiserror` dependency removed in favor of custom errors manually implemented. Having this dependency is probably adding a significant amount of compile time. See https://libreddit.spike.codes/r/rust/comments/gj8inf/rust_structuring_and_handling_errors_in_2020/fqlmknt/?context=3 for some guidelines.
* Checking for WASM compatibility would be nice.
* I never tested the upload functionality. While it seems to compile, it may not actually be possible to upload content.
* It would be good to see more String fields converted to an enum type where appropriate. Here is one example: https://github.com/tonymushah/mangadex-api/blob/a4da7a17ee93dfae3944f05840e39ff332c26ca7/mangadex-api-schema/src/v5/check_token_response.rs#L7

---

Notes about some of the custom deserialization I added:

* [`language_array_or_skip_null`](https://github.com/tonymushah/mangadex-api/blob/main/mangadex-api-schema/src/v5.rs#L495) exists because there are some manga that have `null` in the `availableTranslatedLanguages` field. (Example manga: https://api.mangadex.org/manga/a96676e5-8ae2-425e-b549-7f15dd34a6d8)
* [`localizedstring_array_or_map`](https://github.com/tonymushah/mangadex-api/blob/main/mangadex-api-schema/src/v5.rs#L204) used to be necessary for the `.data.attributes.description` field of https://api.mangadex.org/manga/fe38c4c2-8cea-4f91-9e80-b368172bdd5c but it looks like that has been fixed.
* [`volume_aggregate_array_or_map`](https://github.com/tonymushah/mangadex-api/blob/main/mangadex-api-schema/src/v5.rs#L248) fixes an issue with some manga aggregate results where the `.volumes.0.chapters` field would be an array instead of an object. For example, https://api.mangadex.org/manga/d773c8be-8e82-4ff1-a4e9-46171395319b/aggregate. This one has "none" as a key within `.volumes`: https://api.mangadex.org/manga/14e157c3-7856-4f86-a2d2-8faa86660744/aggregate

**Comment by gondolyr** [comment]
> My intention is not to force the burden of maintaining the original crate if you don't want to. If you would prefer to maintain a fork solely for your reader app, that could be a better path.

There's also the option of leaving the crate in the hands of rust-bus so that they may find a suitable person or group to maintain it.
https://users.rust-lang.org/t/bus-factor-1-for-crates/17046

**Comment by tonymushah** [comment]
Okay, i decided that i will take the ownership of the `mangadex-api` crate.
There is also a lot of things that i want.
But the first thing, i want to add is the OAuth login support since Mangadex doesn't support the old login system.
I already had an [example](https://github.com/tonymushah/mangadex-oauth2-rs-example) but it only work for api.mangadex.dev so i need to wait that Mangadex Auth support other third party clients

**Comment by gondolyr** [comment]
You should have gotten an invitation to become an owner of the `mangadex-api` crate. Let me know if there are any issues.

**Comment by tonymushah** [comment]
Okay, i already validated the ownership on crates.io. Thanks!
