### ISSUE TITLE
Add Rate Limiting Handling

### ISSUE THREAD

**Issue by RiyeUK** [tonymushah/mangadex-api#26]
Rate limits can change depending on the number of load balancers that are active. The API call responses includes header meta data related to these rate limits.

In the short term I would suggest adding these headers to the `mangadex_api_schema::ApiData` struct to allow user code to utilise this meta data.

| Header | Description|
|--------|--------|
| `X-RateLimit-Limit` | Maximal number of requests this endpoint allows per its time period       |
| `X-RateLimit-Remaining` | Remaining number of requests within your quota for the current time period|
| `X-RateLimit-Retry-After` | Timestamp of the end of the current time period, as UNIX timestamp        |

[https://api.mangadex.org/docs/rate-limits/](https://api.mangadex.org/docs/rate-limits/)

**Comment by tonymushah** [comment]
Hello there! 

Firstly, Thank you for posting this interesting issue.

Secondly, I apologize for not responding you sooner, 
I have a lot of projects behind this and I didn't have the time on focusing on this issue.

Thirdly, Your proposition for adding rate limiting handling is interesting, 
but adding field on `mangadex_api_schema::ApiData` would be technical challenge for me.

There is around 30 endpoints that respond with these headers, and each of them have a different response type.
I know that some of them respond with the : `mangadex_api_schema::ApiData`, 
but for the `GET /at-home/server/{id}`, his response type is `mangadex_api_schema::v5::AtHomeServer`.

After re factoring all of the SDK for the new syntax, I come up with an idea that should be 'easy' to implement and noticeable in your development.

We added these struct : 
```rust
/// This `RateLimit` struct contains all the data needed for rate limit handling
/// It can be parsed via a [`reqwest::Response`] or [`reqwest::header::HeaderMap`]
#[derive(Serialize, Debug)]
#[cfg_attr(feature = "non_exhaustive", non_exhaustive)]
pub struct RateLimit {
    /// value from `x-ratelimit-limit` header
    pub limit: u32,
    /// value from `x-ratelimit-remaining` header
    pub remaining: u32,
    /// value from `x-ratelimit-retry-after` header
    /// It's normally an [`i64`] [(Unix timestamp)](https://www.unixtimestamp.com/) 
    /// but can be parsed as a [`crate::MangaDexDateTime`]
    pub retry_after: MangaDexDateTime,
}
```
```rust
/// This struct is used for rate limited endpoint
/// `rate_limit` is for the rate limit metadata
/// `body` is the response data
pub struct Limited<T> {
    pub rate_limit: RateLimit,
    pub body: T,
}
```

The `RateLimit` struct is for the rate limit metadata header. 
And the `Limited<T>` is for handling the metadata.

I know that it might be a strange solution but it's the only one that i come up with.

You can lookup to this linked pull request #87  to see the work progess
